name: "macOS Geo + R (pak) Setup"
description: "Set up R (setup-r@v2), Pandoc, macOS system deps (Homebrew), and install R packages with pak (setup-r-dependencies@v2)."
author: "Montana Climate Office"
runs:
  using: "composite"
  steps:
    # Include checkout so the action is self-contained; safe if already checked out.
    - name: Checkout
      uses: actions/checkout@v6

    # Install R (do NOT use Homebrew's R cask).
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release

    # Pandoc for rmarkdown/quarto pipelines.
    - name: Set up Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    # macOS system dependencies you listed; no R cask here.
    - name: Install Homebrew formulae
      shell: bash
      run: |
        set -euxo pipefail
        brew update
        brew upgrade
        brew cleanup --prune=all --scrub || true
        rm -rf "$(brew --cache)" || true
        brew install apache-arrow udunits gdal node
        brew cleanup --prune=all --scrub || true
        rm -rf "$(brew --cache)" || true

    # Global CLI tool
    - name: Install mapshaper (npm -g)
      shell: bash
      run: |
        set -euxo pipefail
        npm install -g mapshaper

    # Install R packages with pak + caching.
    # We use 'extra-packages' to ensure these are installed even if the repo
    # is not a formal R package with a DESCRIPTION file.
    - name: Install R dependencies (pak + cache)
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: |
          any::arrow?source
          any::sf?source
          any::terra?source
          any::curl
          any::tidyverse
          any::digest
          any::geometa
          any::fs
          any::xml2
          any::jsonlite
          any::tigris
          any::rmapshaper
          any::furrr
          any::future.mirai

    # Optional: quick sanity check
    - name: Verify toolchain
      shell: bash
      run: |
        set -euxo pipefail
        R --version | head -n 1 || true
        pandoc --version | head -n 2 || true
        gdalinfo --version || true
        node --version
        mapshaper -v